openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-static-rabbitmq
components:
  schemas:
    variables:
      type: object
      required:
      - hosts
      - password
      - username
      properties:
        hosts:
          title: Hosts
          type: array
          description: The host list of the RabbitMQ service.
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        port:
          title: Port
          type: number
          description: The port of the RabbitMQ service.
          default: 5672
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 5
        username:
          title: Username
          type: string
          description: The username of the account to access the service.
          x-walrus-ui:
            group: Basic
            order: 3
        password:
          title: Password
          type: string
          description: The password of the account to access the service.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
